deepspeed --num_gpus 4 --master_port=9901 src/train.py \
	--deepspeed ds_config_zero3_bf16.json \
    --stage sft \
    --do_train \
    --model_name_or_path allganize/Llama-3-Alpha-Ko-8B-Instruct \
    --dataset text_to_sql_data \
    --template llama3-text-to-sql \
    --finetuning_type lora \
    --lora_target all \
    --output_dir checkpoint \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --learning_rate 1e-4 \
    --num_train_epochs 10.0 \
    --report_to none \
    --bf16